import turtle
import math
wn = turtle.Screen()
wn.bgcolor("green")
tay = turtle.Turtle()
tay.color("red")
tay.pensize(10)
tay.right(90)
tay.forward(100)
tay.left(90)
tay.forward(100)
tay.left(90)
tay.forward(100)
tay.left(90)
tay.forward(100)
diagonal = math.sqrt(100*100/2)
tay.right(135)
tay.color("black")
tay.forward(diagonal)
tay.right(90)
tay.color("black")
tay.forward(diagonal)

wn.exitonclick()